In [2]:
import pandas as pd

In [4]:
npr = pd.read_csv("npr.csv")

In [6]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [8]:
npr["Article"][7]

'I was standing by the airport exit, debating whether to get a snack, when a young man with a round face approached me. I focused hard to decipher his words. In a thick accent, he asked me to help him find his suitcase. As we walked to baggage claim, I learned his name: Edward Murinzi. This was his very first plane trip. A refugee from the Democratic Republic of Congo, he’d just arrived to begin his American life. Beside the luggage carousel at Washington’s Reagan Airport, he looked out at the two lanes of traffic and the concrete wall beyond. ”So this is America?” he said. From finding his bag to finding his apartment and finding a job, there was a lot for Edward to learn. Later, he acknowledged that while he was standing in the airport looking for his luggage, he felt the magnitude of the task before him. He says questions were zipping around his head: ”How will I start? You get scared. How will I manage?” After he found his bag and I called his caseworker to come and pick him up, we

In [10]:
npr.head(10)

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...
5  I did not want to join yoga class. I hated tho...
6  With a   who has publicly supported the debunk...
7  I was standing by the airport exit, debating w...
8  If movies were trying to be more realistic, pe...
9  Eighteen years ago, on New Year’s Eve, David F...

In [12]:
len(npr)

11992

In [16]:
from sklearn.feature_extraction.text import CountVectorizer 

In [18]:
cv = CountVectorizer(max_df = 0.95, min_df=2, stop_words="english") 

In [20]:
dtm = cv.fit_transform(npr["Article"])

In [22]:
from sklearn.decomposition import LatentDirichletAllocation

In [24]:
LDA = LatentDirichletAllocation(n_components=7,random_state=42)

In [26]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

In [28]:
len(cv.get_feature_names_out())

54777

In [30]:
type(cv.get_feature_names_out())

numpy.ndarray

In [34]:
cv.get_feature_names_out()[50000]

'transcribe'

In [36]:
import random

In [50]:
random_word_id = random.randint(0,54777)
print(cv.get_feature_names_out()[random_word_id])

zambelich


In [52]:
for i in range(10):
    random_word_id = random.randint(0, 54777)
    print(cv.get_feature_names_out()[random_word_id])

npd
largo
marik
knoepfler
desert
banished
novels
audubon
transporting
agonized


In [54]:
len(LDA.components_)

7

In [58]:
LDA.components_.shape

(7, 54777)

In [60]:
len(LDA.components_[0])

54777

In [62]:
single_topic = LDA.components_[0] 

In [64]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [66]:
single_topic.argsort()[-20:]

array([38079, 46581, 48643, 25406, 50426, 10421, 32089, 54403, 18349,
           1, 33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673,
       42561, 42993])

In [68]:
top_word_indices = single_topic.argsort()[-10:]

In [70]:
for index in  top_word_indices:
    print(cv.get_feature_names_out()[index])

new
percent
government
company
million
care
people
health
said
says


In [72]:
from sklearn.decomposition import LatentDirichletAllocation

In [74]:
for index,topic in enumerate(LDA.components_):
    print(f'THE TOP 15 WORDS FOR TOPIC #{index}')
    print([cv.get_feature_names_out()[i] for i in topic.argsort()[-25:]])
    print('/n')

THE TOP 15 WORDS FOR TOPIC #0
['law', 'plan', 'states', 'business', 'pay', 'president', 'state', 'tax', 'insurance', 'trump', 'companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']
/n
THE TOP 15 WORDS FOR TOPIC #1
['russian', 'officials', 'press', 'new', 'country', 'white', 'according', 'attack', 'reported', 'war', 'military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']
/n
THE TOP 15 WORDS FOR TOPIC #2
['long', 'small', 'local', 'said', 'life', 'little', 'know', 'don', 'year', 'make', 'way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']
/n
THE TOP 15 WORDS FOR TOPIC #3
['researchers', 'drug', 'use', 'brain', 'help', 'world', 'research', 'university', 'percent', 'care', 'time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'j

In [76]:
dtm.shape

(11992, 54777)

In [78]:
len(npr)

11992

In [80]:
topic_results = LDA.transform(dtm)

In [82]:
topic_results

array([[1.61040465e-02, 6.83341493e-01, 2.25376318e-04, ...,
        2.99652737e-01, 2.25479379e-04, 2.25497980e-04],
       [3.63424997e-02, 8.86130697e-01, 4.40751747e-04, ...,
        7.57636804e-02, 4.40866779e-04, 4.40835574e-04],
       [3.28569485e-04, 6.96344889e-01, 3.28302105e-04, ...,
        3.02012902e-01, 3.28724083e-04, 3.28352652e-04],
       ...,
       [1.44467964e-02, 1.60696622e-01, 1.73678310e-01, ...,
        2.24636569e-02, 3.98728349e-04, 3.98359730e-04],
       [4.33560738e-04, 3.53196803e-02, 4.33022554e-04, ...,
        9.62512640e-01, 4.33971991e-04, 4.33490254e-04],
       [3.98777533e-01, 2.54376049e-04, 3.59290659e-01, ...,
        2.40914375e-01, 2.54445555e-04, 2.54253739e-04]])

In [84]:
topic_results.shape

(11992, 7)

In [86]:
topic_results[0]

array([1.61040465e-02, 6.83341493e-01, 2.25376318e-04, 2.25369288e-04,
       2.99652737e-01, 2.25479379e-04, 2.25497980e-04])

In [88]:
topic_results[0].round(2)

array([0.02, 0.68, 0.  , 0.  , 0.3 , 0.  , 0.  ])

In [90]:
topic_results[0].argmax()

1

In [92]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [94]:
topic_results.argmax(axis=1)

array([1, 1, 1, ..., 3, 4, 0])

In [100]:
npr['Topic'] = topic_results.argmax(axis=1)      #Axis=1 why we use # Jab new column create karna ho jo existing columns ka operation ho

In [98]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]